FROM rust:slim-bookworm
RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch
WORKDIR /app

CMD ["sh", "-c", "exec cargo watch --poll -w app/${APP_NAME}/src -w lib -w Cargo.toml -x run"]
